"""Block catalog service (PLAN Phase 4 T4.4; §2.3; API-REF §8).

Bundled entries: `services/catalog/bundled/<tag>.json`, one per Appendix B Core Block,
generated by `scripts/extract_hax_properties.py` from the 26.8.1 public build —
haxProperties JSON where the build ships it (18 of 31 tags) and source-verified curated
entries for the inline-only elements (for those the bundled catalog is the ONLY source).

Live merge: with a client and a site, `GET blocks/{tag}?include=haxProperties` (fallback
`GET schemas?filter.kind=haxProperties&filter.webcomponentName={tag}`) refreshes
attributes/slots/example from the server, cached 10 minutes; `GET custom-elements/{tag}`
answers whether the wc-registry knows a tag the catalog does not. Live failures degrade
silently to bundled-only (the routes may be missing, the feature disabled, or the server
offline — the catalog must keep working).

Validation (§2.3): the tag must be known (bundled, live or wc-registry) — unknown tags
raise INVALID_ARGUMENT listing the closest matches; attribute names must be known or
`data-*`/`slot`/`class`/`id`; enum values must be legal. Native HTML tags are always
known and carry no attribute restrictions. `required` is NOT enforced here — the typed
tools fill required attributes themselves.
"""

from __future__ import annotations

import difflib
import json
import time
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from haxcms_mcp.client import HaxcmsClient, site_api
from haxcms_mcp.errors import ErrorCode, HaxcmsMcpError
from haxcms_mcp.services.catalog.hax_properties import entry_from_hax_properties, kebab

BUNDLED_DIR = Path(__file__).resolve().parent / "bundled"

CACHE_SECONDS = 600  # live-merge cache (PLAN §2.3: 10 minutes)

# native HTML the generic add_block accepts without a catalog entry (Appendix B's last
# row has native tools for these; the catalog still needs to KNOW them for validate)
NATIVE_TAGS = frozenset(
    {
        "p",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "div",
        "span",
        "a",
        "img",
        "hr",
        "br",
        "ul",
        "ol",
        "li",
        "dl",
        "dt",
        "dd",
        "table",
        "thead",
        "tbody",
        "tfoot",
        "tr",
        "th",
        "td",
        "caption",
        "blockquote",
        "pre",
        "code",
        "em",
        "strong",
        "b",
        "i",
        "u",
        "s",
        "small",
        "sub",
        "sup",
        "figure",
        "figcaption",
        "video",
        "audio",
        "source",
        "iframe",
        "template",
    }
)

# attributes accepted on any custom element regardless of its catalog entry (§2.3)
UNIVERSAL_ATTRIBUTES = frozenset({"slot", "class", "id"})


class BlockAttribute(BaseModel):
    """One catalog attribute: `{name, type, required, description, enum?}` (§2.3)."""

    name: str
    type: str = "string"
    required: bool = False
    description: str = ""
    enum: list[str] | None = None


class BlockSlot(BaseModel):
    """One catalog slot: `{name, description}` ('default' is the unnamed slot)."""

    name: str
    description: str = ""


class CatalogEntry(BaseModel):
    """A block's full catalog record (§2.3 entry shape + the list_blocks category)."""

    tag: str
    title: str = ""
    description: str = ""
    category: str = ""
    attributes: list[BlockAttribute] = []
    slots: list[BlockSlot] = []
    example_html: str = ""
    agent_notes: str = ""

    def summary(self) -> dict[str, Any]:
        """The list_blocks line: tag, title, one-line description, category."""
        return {
            "tag": self.tag,
            "title": self.title,
            "description": self.description,
            "category": self.category,
        }


def _first_schema(data: Any) -> Any:
    """The first haxProperties record from a GET schemas response (shape varies)."""
    if isinstance(data, dict):
        if "settings" in data or "gizmo" in data:
            return data  # the response IS the props object
        for key in ("schemas", "items", "results", "data"):
            inner = data.get(key)
            if isinstance(inner, list) and inner:
                first = inner[0]
                if isinstance(first, dict):
                    props = first.get("haxProperties")
                    return props if isinstance(props, dict) else first
                return None
    if isinstance(data, list) and data:
        first = data[0]
        if isinstance(first, dict):
            props = first.get("haxProperties")
            return props if isinstance(props, dict) else first
    return None


def _union_by_name(
    live: list[dict[str, Any]], bundled: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    """Live entries win per name; bundled-only names are appended (curated extras).

    The bundled catalog carries source-verified attributes the live haxProperties
    extraction cannot see (developer-group or editor-stripped settings like
    video-player accent-color, a11y-collapse expanded); dropping them on a successful
    live merge would make validation depend on whether a site is addressed.
    """
    names = {entry.get("name") for entry in live}
    return [*live, *(entry for entry in bundled if entry.get("name") not in names)]


def _merge_live(bundled: CatalogEntry | None, live: dict[str, Any], tag: str) -> CatalogEntry:
    """Non-empty live fields win; curated title/description/category/agent_notes stay.

    A live schema without a demoSchema must not wipe the bundled example, so empty
    live values ("", None, [], {}) never overwrite a bundled one. Attributes and slots
    merge as a union by name (live definition wins, bundled-only names are kept).
    """
    data: dict[str, Any] = bundled.model_dump() if bundled is not None else {}
    for field, value in live.items():
        if value not in ("", None, [], {}):
            data[field] = value
    data["tag"] = tag
    if bundled is not None:
        original = bundled.model_dump()
        for field in ("title", "description", "category", "agent_notes"):
            value = getattr(bundled, field)
            if value:
                data[field] = value
        for field in ("attributes", "slots"):
            # union is a no-op when live did not replace the bundled list
            data[field] = _union_by_name(data.get(field) or [], original[field])
    return CatalogEntry.model_validate(data)


class CatalogService:
    """Bundled catalog + best-effort live merge + validation (§2.3)."""

    def __init__(self, client: HaxcmsClient | None = None) -> None:
        self._client = client
        self._bundled: dict[str, CatalogEntry] | None = None
        self._cache: dict[str, tuple[float, Any]] = {}

    @property
    def bundled(self) -> dict[str, CatalogEntry]:
        """Lazily loaded bundled entries keyed by tag."""
        if self._bundled is None:
            entries: dict[str, CatalogEntry] = {}
            for path in sorted(BUNDLED_DIR.glob("*.json")):
                data = json.loads(path.read_text(encoding="utf-8"))
                entry = CatalogEntry.model_validate(data)
                entries[entry.tag] = entry
            self._bundled = entries
        return self._bundled

    def known_tags(self) -> set[str]:
        return set(self.bundled) | NATIVE_TAGS

    async def _cached(self, key: str, fetch: Callable[[], Awaitable[Any]]) -> Any:
        """Best-effort fetch with a 10-minute cache; HaxcmsMcpError → cached None."""
        now = time.monotonic()
        hit = self._cache.get(key)
        if hit is not None and hit[0] > now:
            return hit[1]
        try:
            data = await fetch()
        except HaxcmsMcpError:
            data = None
        self._cache[key] = (now + CACHE_SECONDS, data)
        return data

    async def _live_props(self, client: HaxcmsClient, site: str, tag: str) -> dict[str, Any] | None:
        data = await self._cached(
            f"{site}|block|{tag}",
            lambda: site_api.get_block(client, site, tag, include="haxProperties"),
        )
        props = data.get("haxProperties") if isinstance(data, dict) else None
        if not isinstance(props, dict):
            data = await self._cached(
                f"{site}|schema|{tag}",
                lambda: site_api.list_schemas(
                    client,
                    site,
                    params={
                        "filter.kind": "haxProperties",
                        "filter.webcomponentName": tag,
                    },
                ),
            )
            props = _first_schema(data)
        return props if isinstance(props, dict) else None

    async def get(self, tag: str, *, site: str | None = None) -> CatalogEntry:
        """The merged catalog entry for `tag`; raises INVALID_ARGUMENT when unknown."""
        clean = (tag or "").strip().lower()
        if not clean:
            raise HaxcmsMcpError(
                ErrorCode.INVALID_ARGUMENT,
                "tag must not be empty",
                hint="e.g. p, media-image, self-check — call list_blocks for the catalog",
            )
        client = self._client
        entry = self.bundled.get(clean)
        if entry is None and clean in NATIVE_TAGS:
            return CatalogEntry(
                tag=clean, title=clean, description="native HTML element", category="text"
            )
        if client is not None and site:
            props = await self._live_props(client, site, clean)
            if props is not None:
                live = entry_from_hax_properties(clean, props)
                if live is not None:
                    entry = _merge_live(entry, live, clean)
        if entry is None and client is not None and site:
            # last resort: the live wc-registry knows tags the catalog does not
            registry = await self._cached(
                f"{site}|ce|{clean}",
                lambda: site_api.get_custom_element(client, site, clean),
            )
            if isinstance(registry, dict) and registry:
                entry = CatalogEntry(
                    tag=clean,
                    title=clean,
                    description="custom element from the live wc-registry",
                    category="embed",
                )
        if entry is None:
            closest = difflib.get_close_matches(clean, sorted(self.known_tags()), n=5, cutoff=0.5)
            raise HaxcmsMcpError(
                ErrorCode.INVALID_ARGUMENT,
                f"unknown block tag {tag!r}",
                hint="call list_blocks for the catalog"
                + (f"; closest matches: {', '.join(closest)}" if closest else ""),
                details={"tag": tag, "closest": closest},
            )
        return entry

    async def get_block_schema(self, tag: str, *, site: str | None = None) -> CatalogEntry:
        """The merged catalog record (T4.4 `get_block_schema`)."""
        return await self.get(tag, site=site)

    async def list_blocks(self) -> list[dict[str, Any]]:
        """Catalog summaries (tag, title, one-line description, category), by tag."""
        entries = sorted(self.bundled.values(), key=lambda entry: entry.tag)
        return [entry.summary() for entry in entries]

    async def validate(
        self,
        tag: str,
        attributes: dict[str, Any] | None = None,
        *,
        site: str | None = None,
    ) -> CatalogEntry | None:
        """Check tag + attribute names + enum values; returns the entry used.

        Native HTML tags return None (no schema to validate against); live-registry-only
        tags return None when the merge yielded no attribute list. `None` and `False`
        values are omitted from the rendered block (see build_block_html), so they carry
        nothing to check and are skipped — the typed tools pass every parameter through.
        """
        clean = (tag or "").strip().lower()
        if clean in NATIVE_TAGS:
            return None
        entry = await self.get(clean, site=site)
        if not entry.attributes:
            return None
        attrs = {
            kebab(str(name)): value
            for name, value in (attributes or {}).items()
            if value is not None and value is not False
        }
        known = {attribute.name for attribute in entry.attributes}
        unknown = sorted(
            name
            for name in attrs
            if name not in known
            and name not in UNIVERSAL_ATTRIBUTES
            and not name.startswith("data-")
        )
        if unknown:
            raise HaxcmsMcpError(
                ErrorCode.INVALID_ARGUMENT,
                f"unknown attributes for {clean}: {', '.join(unknown)}",
                hint="known attributes: "
                + (", ".join(sorted(known)) or "(none)")
                + " (plus data-*, slot, class, id)",
                details={"tag": clean, "unknown": unknown, "known": sorted(known)},
            )
        for attribute in entry.attributes:
            if attribute.enum and attribute.name in attrs:
                value = attrs[attribute.name]
                text = value if isinstance(value, str) else json.dumps(value)
                if text not in attribute.enum:
                    raise HaxcmsMcpError(
                        ErrorCode.INVALID_ARGUMENT,
                        f"invalid {attribute.name}={text!r} for {clean}",
                        hint=f"allowed values: {', '.join(attribute.enum)}",
                        details={
                            "tag": clean,
                            "attribute": attribute.name,
                            "allowed": attribute.enum,
                        },
                    )
        return entry
