#!/usr/bin/env python
"""Generate the tool reference from the live registry (PLAN Phase 9 T9.2).

    uv run python scripts/gen_tool_docs.py           # write docs/tools.md
    uv run python scripts/gen_tool_docs.py --check   # exit 1 when the committed file drifts

The output is deterministic: tools render in alphabetical order straight from
`build_server()` with no timestamps, so regenerating an up-to-date tree is a no-op and CI
can simply diff (`--check`). Each tool gets its name, annotations, every parameter with
its schema type / required flag / default, and the first docstring paragraph.
"""

from __future__ import annotations

import argparse
import asyncio
import difflib
import json
import sys
from pathlib import Path
from typing import Any

from haxcms_mcp import __version__
from haxcms_mcp.config import Settings
from haxcms_mcp.server import build_server

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "tools.md"
GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_tool_docs.py from the live tool registry. Do not edit;\n"
    "     run `uv run python scripts/gen_tool_docs.py` and commit (CI checks --check). -->"
)
_NO_DEFAULT = "—"
_MARKER_LINES = {"args", "arguments", "returns", "raises", "yields", "example", "examples"}


def collect_tools() -> list[Any]:
    """Every registered Tool, alphabetically (fresh in-process registry, no network)."""
    server = build_server(Settings(base_url="http://docs.invalid"))
    return sorted(asyncio.run(server.list_tools()), key=lambda tool: tool.name)


def first_paragraph(description: str | None) -> str:
    """The docstring's first paragraph, unwrapped to a single line."""
    text = (description or "").strip()
    lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            if lines:
                break
            continue
        if stripped.rstrip(":").lower() in _MARKER_LINES:
            break
        lines.append(stripped)
    return " ".join(lines)


def schema_type(prop: dict[str, Any]) -> str:
    """Human-readable type for one JSON-schema property (pipes are cell-escaped later)."""
    for key in ("anyOf", "oneOf"):
        members = prop.get(key)
        if isinstance(members, list) and members:
            return " | ".join(schema_type(m) for m in members if isinstance(m, dict))
    if isinstance(prop.get("enum"), list):
        return " | ".join(json.dumps(value) for value in prop["enum"])
    type_ = prop.get("type")
    if type_ == "array":
        items = prop.get("items")
        inner = schema_type(items) if isinstance(items, dict) else "any"
        return f"array[{inner}]"
    if type_ == "object" and isinstance(prop.get("properties"), dict):
        return "object"
    return str(type_ or "any")


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _annotations_line(tool: Any) -> str:
    annotations = tool.annotations
    if annotations is None:
        return "_no annotations_"
    hints = (
        f"read-only: {'yes' if annotations.read_only_hint else 'no'}",
        f"destructive: {'yes' if annotations.destructive_hint else 'no'}",
        f"idempotent: {'yes' if annotations.idempotent_hint else 'no'}",
        f"open-world: {'yes' if annotations.open_world_hint else 'no'}",
    )
    title = annotations.title or tool.name
    return f"**{_cell(str(title))}** — " + " · ".join(hints)


def _parameter_table(tool: Any) -> list[str]:
    parameters = tool.parameters if isinstance(tool.parameters, dict) else {}
    properties = parameters.get("properties")
    if not isinstance(properties, dict) or not properties:
        return ["_No parameters._"]
    required = set(parameters.get("required") or ())
    lines = [
        "| Parameter | Type | Required | Default |",
        "| --- | --- | --- | --- |",
    ]
    for name, prop in properties.items():
        prop = prop if isinstance(prop, dict) else {}
        default = json.dumps(prop["default"]) if "default" in prop else _NO_DEFAULT
        lines.append(
            f"| `{name}` | {_cell(schema_type(prop))} "
            f"| {'yes' if name in required else 'no'} | {_cell(default)} |"
        )
    return lines


def _tool_section(tool: Any) -> list[str]:
    lines = [f"## `{tool.name}`", ""]
    summary = first_paragraph(tool.description)
    if summary:
        lines.extend([summary, ""])
    lines.extend([_annotations_line(tool), ""])
    lines.extend(_parameter_table(tool))
    return lines


def build_docs_text() -> str:
    """The full docs/tools.md text, deterministic byte-for-byte."""
    tools = collect_tools()
    read_only = sum(1 for t in tools if t.annotations and t.annotations.read_only_hint)
    destructive = sum(1 for t in tools if t.annotations and t.annotations.destructive_hint)
    lines = [
        "# HAXcms MCP tool reference",
        "",
        GENERATED_NOTE,
        "",
        f"`haxcms-mcp` {__version__} — {len(tools)} tools "
        f"({read_only} read-only, {destructive} destructive).",
        "",
        "## Index",
        "",
        "| Tool | Title | Read-only | Destructive | Idempotent |",
        "| --- | --- | --- | --- | --- |",
    ]
    for tool in tools:
        annotations = tool.annotations
        title = _cell(str(annotations.title)) if annotations and annotations.title else ""
        flags = (
            (
                "yes" if annotations.read_only_hint else "no",
                "yes" if annotations.destructive_hint else "no",
                "yes" if annotations.idempotent_hint else "no",
            )
            if annotations is not None
            else ("", "", "")
        )
        lines.append(
            f"| [`{tool.name}`](#{tool.name.lower()}) | {title} | "
            f"{flags[0]} | {flags[1]} | {flags[2]} |"
        )
    lines.append("")
    for tool in tools:
        lines.extend(_tool_section(tool))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def check(output_path: Path = OUTPUT_PATH) -> bool:
    """True when the committed file matches a fresh generation (and exists)."""
    if not output_path.exists():
        return False
    return output_path.read_text(encoding="utf-8") == build_docs_text()


def write_docs(output_path: Path = OUTPUT_PATH) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n": generation is byte-identical on every platform (CI diffs it).
    output_path.write_text(build_docs_text(), encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when the committed docs/tools.md drifts",
    )
    args = parser.parse_args(argv)
    if args.check:
        if not check():
            expected = build_docs_text().splitlines(keepends=True)
            actual: list[str] = []
            if OUTPUT_PATH.exists():
                actual = OUTPUT_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
            sys.stderr.write(
                "".join(difflib.unified_diff(actual, expected, "committed", "generated", n=2))
                or f"missing {OUTPUT_PATH}\n"
            )
            sys.stderr.write(
                "tool docs drift: run `uv run python scripts/gen_tool_docs.py` and commit\n"
            )
            return 1
        print("docs/tools.md is up to date")
        return 0
    write_docs()
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
