#!/usr/bin/env python
"""Generate the converter functions from the vendored OpenAPI spec (PLAN T7.4, ADR-0002).

    uv run python scripts/gen_tools.py           # write generated/converters.py
    uv run python scripts/gen_tools.py --check   # exit 1 when the committed file drifts

The output is deterministic: the twelve converters render in CONVERTERS order straight
from specs/system-spec.yaml (pinned 26.8.1) with no timestamps, so regenerating an
up-to-date tree is a no-op and CI can simply diff.

Parameter derivation: an `application/json` request body contributes one `str` parameter
per schema property (the OPTIONAL_FIELDS names default to None; the rest are required);
a `multipart/form-data` body becomes the single `source: str` parameter resolved through
the Sources convention. The OVERRIDES table pins the source-verified deviations from the
spec (Phase 7, recorded in PROGRESS.md): htmlToDocx/htmlToPdf are multipart .html/.htm
file uploads in 26.8.1 despite their spec JSON bodies, and xlsxToCsv reads its sheet
name from the QUERY string.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import textwrap
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "specs" / "system-spec.yaml"
OUTPUT_PATH = ROOT / "src" / "haxcms_mcp" / "generated" / "converters.py"
INIT_PATH = ROOT / "src" / "haxcms_mcp" / "generated" / "__init__.py"
SPEC_LABEL = "26.8.1"
HEADER_LINE = (
    f"# GENERATED by scripts/gen_tools.py from specs/system-spec.yaml ({SPEC_LABEL}). Do not edit."
)

INIT_TEXT = '"""Build-time generated modules (ADR-0002). Do not edit by hand."""\n'

CONVERTERS: tuple[str, ...] = (
    "docxToHtml",
    "htmlToDocx",
    "mdToHtml",
    "htmlToMd",
    "prettyHtml",
    "jsonToYaml",
    "yamlToJson",
    "htmlToPdf",
    "xlsxToCsv",
    "pdfToHtml",
    "pptxToHtml",
    "docxToPdf",
)

DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# Spec property names that are optional even though the schemas carry no `required`
# list (the converters 400 without their payload field; `type` is a documented toggle).
OPTIONAL_FIELDS = frozenset({"type", "base", "sheet"})

# Result handling per operationId:
#   ("text", mimetype)                      - envelope data.contents is the text result
#   ("base64", mimetype, fallback_filename) - data.contents is base64 of a binary file
#   ("raw", mimetype, fallback_filename)    - the response BYTES are the binary file
RESULTS: dict[str, tuple[str, ...]] = {
    "docxToHtml": ("text", "text/html"),
    "mdToHtml": ("text", "text/html"),
    "htmlToMd": ("text", "text/markdown"),
    "prettyHtml": ("text", "text/html"),
    "jsonToYaml": ("text", "application/yaml"),
    "yamlToJson": ("text", "application/json"),
    "xlsxToCsv": ("text", "text/csv"),
    "pdfToHtml": ("text", "text/html"),
    "pptxToHtml": ("text", "text/html"),
    "htmlToDocx": ("base64", DOCX_MIME, "converted.docx"),
    "htmlToPdf": ("base64", "application/pdf", "converted.pdf"),
    "docxToPdf": ("raw", "application/pdf", "converted.pdf"),
}

# Source-verified deviations from the vendored spec (live-probed in Phase 7):
#   * htmlToDocx / htmlToPdf are MULTIPART .html/.htm file uploads in 26.8.1 (the spec's
#     JSON {html} body answers 400 "No file uploaded"); htmlToPdf keeps `base` as a FORM
#     field (validated http(s) URL upstream, else '/').
#   * xlsxToCsv reads the sheet name from the QUERY string (?sheet=), absent from spec;
#     an unknown sheet silently falls back to the first one.
OVERRIDES: dict[str, dict[str, Any]] = {
    "htmlToDocx": {"multipart": True, "form_fields": (), "query_fields": ()},
    "htmlToPdf": {"multipart": True, "form_fields": ("base",), "query_fields": ()},
    "xlsxToCsv": {"query_fields": ("sheet",)},
}

DEVIATION_NOTES: dict[str, str] = {
    "htmlToDocx": (
        "DEVIATION from the vendored spec (source-verified): the 26.8.1 route accepts "
        "ONLY a multipart .html/.htm file upload; the spec's JSON {html} body answers "
        "400 'No file uploaded'."
    ),
    "htmlToPdf": (
        "DEVIATION from the vendored spec (source-verified): multipart .html/.htm file "
        "upload only (like convert_html_to_docx); `base` rides as a FORM field."
    ),
    "xlsxToCsv": (
        "DEVIATION from the vendored spec (source-verified): the sheet name rides as a "
        "QUERY parameter (?sheet=); an unknown sheet silently falls back to the first."
    ),
}

CHROME_OPERATIONS = frozenset({"htmlToPdf", "docxToPdf"})
CHROME_NOTE = (
    "NEEDS CHROME on the HAXcms server (puppeteer-core; PUPPETEER_EXECUTABLE_PATH or a "
    "system Chrome) - without it the conversion fails upstream."
)

FIELD_NOTES: dict[str, str] = {
    "base": (
        "optional base URL for resolving relative links (FORM field; the server wants "
        "an http(s) URL and defaults to '/')"
    ),
    "sheet": "optional sheet name to convert (QUERY parameter)",
}

EXTRA_NOTES: dict[str, str] = {
    "xlsxToCsv": "the sheetNames/selectedSheet extras ride along",
    "pptxToHtml": "the extracted slide images ride along in the `files` extra",
}

IMPORTS_BLOCK = """\
from __future__ import annotations

from pathlib import Path
from typing import Any

from haxcms_mcp.client import HaxcmsClient, system_api
from haxcms_mcp.config import Settings
from haxcms_mcp.services import conversion
from haxcms_mcp.services.files.sources import resolve_source
"""


def camel_to_snake(operation_id: str) -> str:
    """docxToHtml -> docx_to_html (so the function is convert_docx_to_html)."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", operation_id).lower()


def load_operations(spec: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """operationId -> POST operation object for the twelve converters."""
    found: dict[str, dict[str, Any]] = {}
    paths = spec.get("paths")
    if not isinstance(paths, dict):
        paths = {}
    for entry in paths.values():
        if not isinstance(entry, dict):
            continue
        post = entry.get("post")
        if not isinstance(post, dict):
            continue
        operation_id = post.get("operationId")
        if isinstance(operation_id, str) and operation_id in CONVERTERS:
            found[operation_id] = post
    missing = [name for name in CONVERTERS if name not in found]
    if missing:
        raise SystemExit(f"spec is missing converter operations: {', '.join(missing)}")
    return found


def _request_content(operation: dict[str, Any]) -> dict[str, Any]:
    body = operation.get("requestBody")
    content = body.get("content") if isinstance(body, dict) else None
    return content if isinstance(content, dict) else {}


def has_multipart_body(operation: dict[str, Any]) -> bool:
    return "multipart/form-data" in _request_content(operation)


def multipart_file_description(operation: dict[str, Any]) -> str:
    schema = (_request_content(operation).get("multipart/form-data") or {}).get("schema") or {}
    prop = (schema.get("properties") or {}).get("file") or {}
    description = prop.get("description") if isinstance(prop, dict) else None
    return str(description) if description else "file to convert"


def json_fields(operation: dict[str, Any]) -> list[tuple[str, str]]:
    """(name, description) per application/json property, in spec order."""
    schema = (_request_content(operation).get("application/json") or {}).get("schema") or {}
    properties = schema.get("properties")
    if not isinstance(properties, dict):
        return []
    fields: list[tuple[str, str]] = []
    for name, prop in properties.items():
        description = prop.get("description") if isinstance(prop, dict) else None
        fields.append((str(name), str(description) if description else ""))
    return fields


def _wrap(text: str) -> list[str]:
    return textwrap.fill(text, width=88, initial_indent="    ", subsequent_indent="    ").split(
        "\n"
    )


def _docstring(op_id: str, operation: dict[str, Any], *, multipart: bool) -> list[str]:
    result = RESULTS[op_id]
    summary = str(operation.get("summary") or f"Convert via {op_id}").strip().rstrip(".")
    lines = [f'    """{summary}.', ""]
    if op_id in DEVIATION_NOTES:
        lines.extend(_wrap(DEVIATION_NOTES[op_id]))
    if op_id in CHROME_OPERATIONS:
        lines.extend(_wrap(CHROME_NOTE))
    if multipart:
        lines.extend(
            _wrap(
                "`source`: a path / URL / data: / base64: file (Sources convention), "
                f"sent as the multipart file part ({multipart_file_description(operation)})."
            )
        )
        override = OVERRIDES.get(op_id, {})
        for field in (*override.get("form_fields", ()), *override.get("query_fields", ())):
            note = FIELD_NOTES.get(field, "")
            lines.extend(_wrap(f"`{field}`: {note}." if note else f"`{field}`."))
    else:
        lines.extend(_wrap("JSON body fields:"))
        for name, description in json_fields(operation):
            optional = name in OPTIONAL_FIELDS
            label = f"`{name}`" + ("" if optional else " (required)")
            lines.extend(_wrap(f"{label}: {description}." if description else f"{label}."))
    lines.append("")
    if result[0] == "text":
        extra = EXTRA_NOTES.get(op_id, "upstream extras ride along")
        lines.extend(_wrap(f"Returns {{text, mimetype={result[1]}}}; {extra}."))
    else:
        lines.extend(
            _wrap(
                "The binary result is written under the Output Directory; returns "
                "{path, bytes, mimetype, filename}."
            )
        )
    lines.append('    """')
    return lines


def render_converter(op_id: str, operation: dict[str, Any]) -> str:
    """Render one convert_<snake> function: derived parameters, notes and body."""
    override = OVERRIDES.get(op_id, {})
    result = RESULTS[op_id]
    multipart = bool(override.get("multipart", False)) or has_multipart_body(operation)
    name = f"convert_{camel_to_snake(op_id)}"

    params = ["    client: HaxcmsClient,"]
    body: list[str] = []
    call_args: list[str] = []

    if multipart:
        params.extend(["    settings: Settings,", "    source: str,"])
        form_fields = tuple(override.get("form_fields", ()))
        query_fields = tuple(override.get("query_fields", ()))
        for field in (*form_fields, *query_fields):
            params.append(f"    {field}: str | None = None,")
        body.append("resolved = await resolve_source(source, settings)")
        body.append(
            'files = {"file-upload": (resolved.filename, resolved.data, resolved.mimetype)}'
        )
        call_args.append("files=files")
        if form_fields:
            body.append("form: dict[str, Any] = {}")
            for field in form_fields:
                body.append(f"if {field} is not None:")
                body.append(f'    form["{field}"] = {field}')
            call_args.append("data=form or None")
        for field in query_fields:
            body.append(f'params = {{"{field}": {field}}} if {field} is not None else None')
            call_args.append("params=params")
    else:
        fields = json_fields(operation)
        required = [(field, desc) for field, desc in fields if field not in OPTIONAL_FIELDS]
        optional = [(field, desc) for field, desc in fields if field in OPTIONAL_FIELDS]
        params.extend(f"    {field}: str," for field, _ in required)
        params.extend(f"    {field}: str | None = None," for field, _ in optional)
        literal = ", ".join(f'"{field}": {field}' for field, _ in required)
        body.append(f"payload: dict[str, Any] = {{{literal}}}")
        for field, _ in optional:
            body.append(f"if {field} is not None:")
            body.append(f'    payload["{field}"] = {field}')
        call_args.append("json=payload")

    joined_args = ", ".join(call_args)
    if result[0] == "text":
        body.append(f'data = await system_api.action(client, "{op_id}", {joined_args})')
        body.append(f'return conversion.text_result(data, "{result[1]}")')
    elif result[0] == "base64":
        body.append(f'data = await system_api.action(client, "{op_id}", {joined_args})')
        body.extend(
            [
                "return conversion.write_base64(",
                "    data,",
                f'    mimetype="{result[1]}",',
                f'    fallback_filename="{result[2]}",',
                "    output_dir=settings.output_dir,",
                ")",
            ]
        )
    else:  # raw bytes (docxToPdf streams application/pdf past the envelope)
        suffix = Path(str(result[2])).suffix
        body.append(
            f'content = await system_api.action(client, "{op_id}", {joined_args}, raw=True)'
        )
        body.append(f'filename = Path(resolved.filename).stem + "{suffix}"')
        body.extend(
            [
                "return conversion.write_bytes(",
                "    content,",
                f'    mimetype="{result[1]}",',
                "    filename=filename,",
                "    output_dir=settings.output_dir,",
                ")",
            ]
        )

    lines = [f"async def {name}(", *params, ") -> dict[str, Any]:"]
    lines.extend(_docstring(op_id, operation, multipart=multipart))
    # body entries carry their RELATIVE indent (if-bodies 4, call continuations 4);
    # the function level adds the outer 4 spaces.
    lines.extend(f"    {line}" for line in body)
    return "\n".join(lines)


def build_module_text() -> str:
    """The full generated module, deterministic byte-for-byte."""
    spec = yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    operations = load_operations(spec)
    module_doc = (
        '"""The twelve converter functions (PLAN Phase 7 T7.4, ADR-0002).\n'
        "\n"
        "Generated at build time from the vendored OpenAPI spec by scripts/gen_tools.py;\n"
        "`--check` fails CI when this file drifts from the spec plus its override table.\n"
        "Input deviations from the spec (source-verified in Phase 7) are noted per function.\n"
        '"""\n'
    )
    header = f"{HEADER_LINE}\n{module_doc}\n{IMPORTS_BLOCK}"
    functions = [render_converter(op_id, operations[op_id]) for op_id in CONVERTERS]
    return header.rstrip("\n") + "\n\n\n" + "\n\n\n".join(functions) + "\n"


def check(output_path: Path = OUTPUT_PATH) -> bool:
    """True when the committed file matches a fresh generation (and exists)."""
    if not output_path.exists():
        return False
    return output_path.read_text(encoding="utf-8") == build_module_text()


def write_module(output_path: Path = OUTPUT_PATH) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not INIT_PATH.exists():
        INIT_PATH.write_text(INIT_TEXT, encoding="utf-8", newline="\n")
    # newline="\n": generation is byte-identical on every platform (CI diffs it).
    output_path.write_text(build_module_text(), encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when the committed generated/converters.py drifts",
    )
    args = parser.parse_args(argv)
    if args.check:
        if not INIT_PATH.exists() or not check():
            expected = build_module_text().splitlines(keepends=True)
            actual: list[str] = []
            if OUTPUT_PATH.exists():
                actual = OUTPUT_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
            sys.stderr.write(
                "".join(difflib.unified_diff(actual, expected, "committed", "generated", n=2))
                or f"missing {OUTPUT_PATH}\n"
            )
            sys.stderr.write(
                "converter tools drift: run `uv run python scripts/gen_tools.py` and commit\n"
            )
            return 1
        print("generated/converters.py is up to date")
        return 0
    write_module()
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
