"""Unit tests for the converter generator (PLAN T7.4, ADR-0002).

scripts/gen_tools.py is not a package module, so it is loaded from its path. The tests
never touch the committed src/haxcms_mcp/generated/ tree: drift behaviour runs against
tmp_path, and everything else inspects build_module_text() in memory.
"""

from __future__ import annotations

import ast
import importlib.util
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

GEN_PATH = Path(__file__).resolve().parents[2] / "scripts" / "gen_tools.py"


def _load_generator() -> object:
    spec = importlib.util.spec_from_file_location("gen_tools_under_test", GEN_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gen_tools = _load_generator()
MODULE_TEXT: str = gen_tools.build_module_text()
TREE = ast.parse(MODULE_TEXT)
FUNCTIONS: dict[str, ast.AsyncFunctionDef] = {
    node.name: node for node in TREE.body if isinstance(node, ast.AsyncFunctionDef)
}


def _segment(name: str) -> str:
    source = ast.get_source_segment(MODULE_TEXT, FUNCTIONS[name])
    assert source is not None, name
    return source


def _param_names(name: str) -> list[str]:
    return [arg.arg for arg in FUNCTIONS[name].args.args]


def test_generation_is_deterministic() -> None:
    assert gen_tools.build_module_text() == MODULE_TEXT


def test_module_compiles_and_header_is_first_line() -> None:
    compile(MODULE_TEXT, "converters.py", "exec")
    first = MODULE_TEXT.splitlines()[0]
    assert first == (
        "# GENERATED by scripts/gen_tools.py from specs/system-spec.yaml (26.8.1). Do not edit."
    )


def test_all_twelve_converter_functions_exist() -> None:
    expected = {f"convert_{gen_tools.camel_to_snake(op)}" for op in gen_tools.CONVERTERS}
    assert len(gen_tools.CONVERTERS) == 12
    assert set(FUNCTIONS) == expected


def test_camel_to_snake() -> None:
    assert gen_tools.camel_to_snake("docxToHtml") == "docx_to_html"
    assert gen_tools.camel_to_snake("htmlToDocx") == "html_to_docx"
    assert gen_tools.camel_to_snake("prettyHtml") == "pretty_html"
    assert gen_tools.camel_to_snake("xlsxToCsv") == "xlsx_to_csv"
    assert gen_tools.camel_to_snake("jsonToYaml") == "json_to_yaml"


@pytest.mark.parametrize(
    ("function", "params"),
    [
        # JSON ops: one str per spec property; OPTIONAL_FIELDS default to None
        ("convert_md_to_html", ["client", "md", "type"]),
        ("convert_html_to_md", ["client", "html", "type"]),
        ("convert_pretty_html", ["client", "html", "type"]),
        ("convert_json_to_yaml", ["client", "json", "type"]),
        ("convert_yaml_to_json", ["client", "yaml", "type"]),
        # multipart ops: the Sources convention replaces the spec file part
        ("convert_docx_to_html", ["client", "settings", "source"]),
        ("convert_pdf_to_html", ["client", "settings", "source"]),
        ("convert_pptx_to_html", ["client", "settings", "source"]),
        # OVERRIDES beat the spec: htmlToDocx is multipart (no `html` param),
        # htmlToPdf keeps base as a FORM field, xlsxToCsv takes the sheet QUERY param
        ("convert_html_to_docx", ["client", "settings", "source"]),
        ("convert_html_to_pdf", ["client", "settings", "source", "base"]),
        ("convert_xlsx_to_csv", ["client", "settings", "source", "sheet"]),
        ("convert_docx_to_pdf", ["client", "settings", "source"]),
    ],
)
def test_parameter_derivation(function: str, params: list[str]) -> None:
    assert _param_names(function) == params


def test_optional_parameters_default_to_none() -> None:
    for name, node in FUNCTIONS.items():
        defaults = node.args.defaults
        optional = len(defaults)
        assert optional <= 1, name
        if optional:
            assert isinstance(defaults[0], ast.Constant) and defaults[0].value is None, name
            assert node.args.args[-1].arg in {"type", "base", "sheet"}, name


def test_json_ops_post_the_spec_payload() -> None:
    segment = _segment("convert_md_to_html")
    assert 'payload: dict[str, Any] = {"md": md}' in segment
    assert 'payload["type"] = type' in segment
    assert 'system_api.action(client, "mdToHtml", json=payload)' in segment


def test_multipart_ops_use_the_sources_convention() -> None:
    segment = _segment("convert_docx_to_html")
    assert "await resolve_source(source, settings)" in segment
    assert '{"file-upload": (resolved.filename, resolved.data, resolved.mimetype)}' in segment
    assert 'system_api.action(client, "docxToHtml", files=files)' in segment


def test_override_wiring() -> None:
    pdf = _segment("convert_html_to_pdf")
    assert 'form["base"] = base' in pdf
    assert "data=form or None" in pdf
    csv = _segment("convert_xlsx_to_csv")
    assert 'params = {"sheet": sheet} if sheet is not None else None' in csv
    assert "params=params" in csv


def test_result_shapes() -> None:
    assert 'return conversion.text_result(data, "text/html")' in _segment("convert_docx_to_html")
    assert 'return conversion.text_result(data, "text/csv")' in _segment("convert_xlsx_to_csv")
    assert "conversion.write_base64(" in _segment("convert_html_to_docx")
    # docxToPdf streams raw application/pdf past the envelope
    raw = _segment("convert_docx_to_pdf")
    assert 'system_api.action(client, "docxToPdf", files=files, raw=True)' in raw
    assert 'Path(resolved.filename).stem + ".pdf"' in raw
    assert "conversion.write_bytes(" in raw
    # only the two binary base64 ops and the raw op touch the output directory
    for name in FUNCTIONS:
        touched = "settings.output_dir" in _segment(name)
        assert touched == (
            name
            in {
                "convert_html_to_docx",
                "convert_html_to_pdf",
                "convert_docx_to_pdf",
            }
        ), name
    for name in FUNCTIONS:
        assert ("raw=True" in _segment(name)) == (name == "convert_docx_to_pdf"), name


def test_docstring_notes() -> None:
    assert "DEVIATION from the vendored spec" in _segment("convert_html_to_docx")
    assert "DEVIATION from the vendored spec" in _segment("convert_html_to_pdf")
    assert "DEVIATION from the vendored spec" in _segment("convert_xlsx_to_csv")
    assert "NEEDS CHROME" in _segment("convert_html_to_pdf")
    assert "NEEDS CHROME" in _segment("convert_docx_to_pdf")
    # the spec's own file/field descriptions land in the docstrings
    assert "Word document (.docx or .doc) to convert" in _segment("convert_docx_to_html")
    assert "treated as a URL to fetch" in _segment("convert_md_to_html")
    assert "sheetNames/selectedSheet" in _segment("convert_xlsx_to_csv")


def test_tables_are_consistent() -> None:
    ops = set(gen_tools.CONVERTERS)
    assert set(gen_tools.RESULTS) == ops
    assert set(gen_tools.CHROME_OPERATIONS) <= ops
    assert set(gen_tools.OVERRIDES) <= ops
    assert set(gen_tools.CHROME_OPERATIONS) == {"htmlToPdf", "docxToPdf"}
    assert set(gen_tools.RESULTS["docxToPdf"]) == {"raw", "application/pdf", "converted.pdf"}


def test_check_detects_drift(tmp_path: Path) -> None:
    target = tmp_path / "converters.py"
    assert gen_tools.check(target) is False  # missing
    target.write_text(MODULE_TEXT, encoding="utf-8")
    assert gen_tools.check(target) is True  # up to date
    target.write_text(MODULE_TEXT + "\n# hand edit\n", encoding="utf-8")
    assert gen_tools.check(target) is False  # drifted


def test_write_module_is_check_clean_and_lf(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(gen_tools, "INIT_PATH", tmp_path / "__init__.py")
    target = tmp_path / "generated" / "converters.py"
    gen_tools.write_module(target)
    assert gen_tools.check(target) is True
    assert b"\r\n" not in target.read_bytes()  # LF-only on every platform
    assert (tmp_path / "__init__.py").read_text(encoding="utf-8") == gen_tools.INIT_TEXT
